In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.python.keras.layers import Dense

x = np.array([[200.0, 170.0]])
layer_1 = Dense(units = 3, activation = 'sigmoid')
a1 = layer_1(x)
a1.numpy()

array([[0.000000e+00, 1.645485e-38, 0.000000e+00]], dtype=float32)

In [ ]:
weights, biases = layer_1.get_weights()
print("Weights:", weights)
print("Biases:", biases)

Weights: [[ 0.8185607  -0.8663975   1.0814984 ]
 [ 0.7494832  -0.79762244 -0.00185299]]
Biases: [0. 0. 0.]


In [27]:
from sklearn.datasets import make_blobs

centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

print("Feature matrix shape:", X.shape)
print("Labels shape:", y.shape)

Feature matrix shape: (1000, 20)
Labels shape: (1000,)


In [21]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy


In [32]:
preferred_model = Sequential(
    [
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'linear')   #<-- Note
    ]
)
preferred_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),  #<-- Note
    optimizer=tf.keras.optimizers.Adam(0.001),
)

preferred_model.fit(
    X_train,y_train,
    epochs=10
)


Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.4170
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6034
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2748
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1526
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0966
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0819
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0686
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0540
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0497
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0441


In [35]:
p_preferred = preferred_model.predict(X_train)
for i in range(5):
    print(f"{p_preferred[i]}: {np.argmax(p_preferred[i])}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[-1.7931876  -2.822961    2.85769    -0.16450341]: 2
[ 3.8684974 -1.1814828 -5.67044   -7.867208 ]: 0
[ 2.5605693  -0.42848814 -4.5383625  -6.1505575 ]: 0
[-2.0594409  3.1179247 -2.826558  -2.8832917]: 1
[-0.24888018 -5.1510262   5.7723737  -3.7639096 ]: 2
